ci: debug dependabot snapshot updates

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,7 +26,19 @@ jobs:
           git config user.name snapshots
           git config user.email snapshots@users.noreply.github.com
           git status
+          # debug https://github.com/tekumara/python-typed-template/issues/126
+          git ls-remote
           git add .
           if git commit -m "chore: update snapshots"; then
             git push
           fi
+      - name: Check branch name
+        run: |
+          BRANCH_NAME="${{ github.head_ref }}"
+          if [[ "$BRANCH_NAME" == *"dependabot"* ]]; then
+            echo "Fail to allow debugging"
+            exit 1
+          fi
+      - name: Start sshx session on failed manual run or retry
+        if: ${{ failure() && (github.event_name == 'workflow_dispatch' || github.run_attempt > 1) }}
+        run: curl -sSf https://sshx.io/get | sh && sshx
